name: 部署最新代码
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          repository: '1345695/edcloudwasm'
      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: 修改配置文件
        run: |
          sed -i '/cpu_ms/d' wrangler.toml
          sed -i '/\[limits\]/d' wrangler.toml
      - name: 安装依赖并尝试构建
        run: |
          if [ -f "package.json" ]; then
            npm install
            npm run build --if-present
          fi
      - name: 部署到CloudflareWorkers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
